branch-defaults:
  default:
    environment: lottery-dev
    group_suffix: null
global:
  application_name: lottery
  default_ec2_keyname: null
  default_platform: PHP 5.6
  default_region: ap-southeast-1
  profile: eb-cli
  sc: null
